{
 "title": "Regime Forecasting",
 "time": { "from": "2025-07-22T11:11:49.282Z", "to": "2025-07-23T02:15:50.717Z" },
 "panels": [
  {
   "title": "Inference Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(prediction_requests_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Inference Latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "rate(inference_latency_seconds_sum[5m]) / rate(inference_latency_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "App Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"fastapi-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(prediction_requests_total)", "legendFormat": "__auto" }
   ]
  }
 ]
}